package jmusic.player.view;

import jmusic.player.controller.MainWindowViewController;

/**
 * Main window class for the JMusic player
 * @author Ricardo Casanova
 * @version 1.0.1
 * @since JMusic 1.0.0
 */
public final class MainWindow extends MyOwnJFrame
{

    /**
     * Creates new form MainWindow
     */
    public MainWindow()
    {
        initComponents();
        initMyOwnComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jBNext = new javax.swing.JButton();
        jBPlay = new javax.swing.JButton();
        jBStop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLMusicList = new javax.swing.JList();
        jLDisplay = new javax.swing.JLabel();
        jBShuffle = new javax.swing.JButton();
        jBPrev = new javax.swing.JButton();
        jLRepeatSong = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMJMusicPlayer = new javax.swing.JMenu();
        jMIAbout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMIQuit = new javax.swing.JMenuItem();
        jMControls = new javax.swing.JMenu();
        jMIPlay = new javax.swing.JMenuItem();
        jMINext = new javax.swing.JMenuItem();
        jMIPrevious = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMIShuffle = new javax.swing.JMenuItem();
        jCBMIRepeat = new javax.swing.JCheckBoxMenuItem();
        jCBMIRepeatFromTheBeginning = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jBNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmusic/player/view/images/IBNext.png"))); // NOI18N
        jBNext.setBorder(null);
        jBNext.setSize(new java.awt.Dimension(30, 30));
        jBNext.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBNextActionPerformed(evt);
            }
        });
        getContentPane().add(jBNext);
        jBNext.setBounds(100, 10, 30, 30);

        jBPlay.setBackground(new java.awt.Color(255, 255, 255));
        jBPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmusic/player/view/images/IBPlay.png"))); // NOI18N
        jBPlay.setBorder(null);
        jBPlay.setBorderPainted(false);
        jBPlay.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBPlayActionPerformed(evt);
            }
        });
        getContentPane().add(jBPlay);
        jBPlay.setBounds(30, 10, 81, 50);

        jBStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmusic/player/view/images/IBStop.png"))); // NOI18N
        jBStop.setBorder(null);
        jBStop.setBorderPainted(false);
        jBStop.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBStopActionPerformed(evt);
            }
        });
        getContentPane().add(jBStop);
        jBStop.setBounds(120, 10, 81, 50);

        jLMusicList.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "01 Don't Go Away", "02 Lord Don't Slow Me Down", "03 Parklife", "04 Bring The Light", "05 Fantasmic", "06 Loser", "07 No Hope", "08 Falling In Love (Is Hard On The Knees)", "09 Push It" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jLMusicList.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLMusicListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jLMusicList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 80, 286, 140);

        jLDisplay.setBackground(new java.awt.Color(204, 204, 204));
        jLDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDisplay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLDisplay.setOpaque(true);
        getContentPane().add(jLDisplay);
        jLDisplay.setBounds(200, 10, 286, 50);

        jBShuffle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmusic/player/view/images/shuffle.png"))); // NOI18N
        jBShuffle.setBorder(null);
        jBShuffle.setSize(new java.awt.Dimension(20, 20));
        jBShuffle.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBShuffleActionPerformed(evt);
            }
        });
        getContentPane().add(jBShuffle);
        jBShuffle.setBounds(10, 230, 20, 20);

        jBPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmusic/player/view/images/IBPrev.png"))); // NOI18N
        jBPrev.setBorder(null);
        jBPrev.setSize(new java.awt.Dimension(30, 30));
        jBPrev.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBPrevActionPerformed(evt);
            }
        });
        getContentPane().add(jBPrev);
        jBPrev.setBounds(10, 10, 30, 30);

        jLRepeatSong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmusic/player/view/images/IBRepeat.png"))); // NOI18N
        jLRepeatSong.setSize(new java.awt.Dimension(20, 20));
        getContentPane().add(jLRepeatSong);
        jLRepeatSong.setBounds(40, 230, 20, 20);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 230, 480, 20);

        jMJMusicPlayer.setText("jMusic Player");

        jMIAbout.setText("About jMusic Player");
        jMIAbout.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMIAboutActionPerformed(evt);
            }
        });
        jMJMusicPlayer.add(jMIAbout);
        jMJMusicPlayer.add(jSeparator1);

        jMIQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.META_MASK));
        jMIQuit.setText("Quit");
        jMIQuit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMIQuitActionPerformed(evt);
            }
        });
        jMJMusicPlayer.add(jMIQuit);

        jMenuBar1.add(jMJMusicPlayer);

        jMControls.setText("Controls");

        jMIPlay.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.META_MASK));
        jMIPlay.setText("Play");
        jMIPlay.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMIPlayActionPerformed(evt);
            }
        });
        jMControls.add(jMIPlay);

        jMINext.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.META_MASK));
        jMINext.setText("Next");
        jMINext.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMINextActionPerformed(evt);
            }
        });
        jMControls.add(jMINext);

        jMIPrevious.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.META_MASK));
        jMIPrevious.setText("Previous");
        jMIPrevious.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMIPreviousActionPerformed(evt);
            }
        });
        jMControls.add(jMIPrevious);
        jMControls.add(jSeparator2);

        jMIShuffle.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.META_MASK));
        jMIShuffle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmusic/player/view/images/shuffle.png"))); // NOI18N
        jMIShuffle.setText("Shuffle");
        jMIShuffle.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMIShuffleActionPerformed(evt);
            }
        });
        jMControls.add(jMIShuffle);

        jCBMIRepeat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.META_MASK));
        jCBMIRepeat.setText("Repeat");
        jCBMIRepeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmusic/player/view/images/IBRepeat.png"))); // NOI18N
        jCBMIRepeat.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCBMIRepeatActionPerformed(evt);
            }
        });
        jMControls.add(jCBMIRepeat);

        jCBMIRepeatFromTheBeginning.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.META_MASK));
        jCBMIRepeatFromTheBeginning.setText("Repeat from the beginning");
        jCBMIRepeatFromTheBeginning.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCBMIRepeatFromTheBeginningActionPerformed(evt);
            }
        });
        jMControls.add(jCBMIRepeatFromTheBeginning);

        jMenuBar1.add(jMControls);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-502)/2, (screenSize.height-303)/2, 502, 303);
    }// </editor-fold>//GEN-END:initComponents

    private void initMyOwnComponents()
    {
        MainWindowViewController.initOutlets(this, jBPlay, jLMusicList, jLDisplay, jCBMIRepeat, jLRepeatSong, jCBMIRepeatFromTheBeginning, jMIPlay);
    }
    private void jBPlayActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBPlayActionPerformed
    {//GEN-HEADEREND:event_jBPlayActionPerformed
        MainWindowViewController.changeLogicButtons();
    }//GEN-LAST:event_jBPlayActionPerformed

    private void jBStopActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBStopActionPerformed
    {//GEN-HEADEREND:event_jBStopActionPerformed
        MainWindowViewController.stopSong();
    }//GEN-LAST:event_jBStopActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        MainWindowViewController.shutdown();
    }//GEN-LAST:event_formWindowClosing

    private void jLMusicListMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMusicListMouseClicked
    {//GEN-HEADEREND:event_jLMusicListMouseClicked
        MainWindowViewController.validateDoubleClic();
    }//GEN-LAST:event_jLMusicListMouseClicked

    private void jBShuffleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBShuffleActionPerformed
    {//GEN-HEADEREND:event_jBShuffleActionPerformed
        MainWindowViewController.shuffle();
    }//GEN-LAST:event_jBShuffleActionPerformed

    private void jBNextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBNextActionPerformed
    {//GEN-HEADEREND:event_jBNextActionPerformed
        MainWindowViewController.nextSong();
    }//GEN-LAST:event_jBNextActionPerformed

    private void jBPrevActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBPrevActionPerformed
    {//GEN-HEADEREND:event_jBPrevActionPerformed
        MainWindowViewController.prevSong();
    }//GEN-LAST:event_jBPrevActionPerformed

    private void jMIQuitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMIQuitActionPerformed
    {//GEN-HEADEREND:event_jMIQuitActionPerformed
        MainWindowViewController.shutdown();
        System.exit(0);
    }//GEN-LAST:event_jMIQuitActionPerformed

    private void jMIAboutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMIAboutActionPerformed
    {//GEN-HEADEREND:event_jMIAboutActionPerformed
        MainWindowViewController.goToTheNexWindowFromHere(this);
    }//GEN-LAST:event_jMIAboutActionPerformed

    private void jCBMIRepeatActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCBMIRepeatActionPerformed
    {//GEN-HEADEREND:event_jCBMIRepeatActionPerformed
        MainWindowViewController.repeatSong();
    }//GEN-LAST:event_jCBMIRepeatActionPerformed

    private void jMIShuffleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMIShuffleActionPerformed
    {//GEN-HEADEREND:event_jMIShuffleActionPerformed
        MainWindowViewController.shuffle();
    }//GEN-LAST:event_jMIShuffleActionPerformed

    private void jMIPreviousActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMIPreviousActionPerformed
    {//GEN-HEADEREND:event_jMIPreviousActionPerformed
        MainWindowViewController.prevSong();
    }//GEN-LAST:event_jMIPreviousActionPerformed

    private void jMINextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMINextActionPerformed
    {//GEN-HEADEREND:event_jMINextActionPerformed
        MainWindowViewController.nextSong();
    }//GEN-LAST:event_jMINextActionPerformed

    private void jMIPlayActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMIPlayActionPerformed
    {//GEN-HEADEREND:event_jMIPlayActionPerformed
        MainWindowViewController.changeLogicButtons();
    }//GEN-LAST:event_jMIPlayActionPerformed

    private void jCBMIRepeatFromTheBeginningActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCBMIRepeatFromTheBeginningActionPerformed
    {//GEN-HEADEREND:event_jCBMIRepeatFromTheBeginningActionPerformed
        MainWindowViewController.repeatSongsFromTheBeginning();
    }//GEN-LAST:event_jCBMIRepeatFromTheBeginningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBNext;
    private javax.swing.JButton jBPlay;
    private javax.swing.JButton jBPrev;
    private javax.swing.JButton jBShuffle;
    private javax.swing.JButton jBStop;
    private javax.swing.JCheckBoxMenuItem jCBMIRepeat;
    private javax.swing.JCheckBoxMenuItem jCBMIRepeatFromTheBeginning;
    private javax.swing.JLabel jLDisplay;
    private javax.swing.JList jLMusicList;
    private javax.swing.JLabel jLRepeatSong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMControls;
    private javax.swing.JMenuItem jMIAbout;
    private javax.swing.JMenuItem jMINext;
    private javax.swing.JMenuItem jMIPlay;
    private javax.swing.JMenuItem jMIPrevious;
    private javax.swing.JMenuItem jMIQuit;
    private javax.swing.JMenuItem jMIShuffle;
    private javax.swing.JMenu jMJMusicPlayer;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
