/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MainWindowViewController;

/**
 *
 * @author ricardocasanova
 */
public class MainWindow extends MyOwnJFrame
{

    /**
     * Creates new form MainWindow
     */
    public MainWindow()
    {
        initComponents();
        initMyOwnComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLInfo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMIAbout = new javax.swing.JMenuItem();
        JMControls = new javax.swing.JMenu();
        jMINextSong = new javax.swing.JMenuItem();
        jCBMIRepeatFromTheBeginning = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLInfo.setBackground(new java.awt.Color(204, 204, 204));
        jLInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLInfo.setOpaque(true);

        jMenu1.setText("File");

        jMIAbout.setText("About");
        jMIAbout.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMIAboutActionPerformed(evt);
            }
        });
        jMenu1.add(jMIAbout);

        jMenuBar1.add(jMenu1);

        JMControls.setText("Controls");

        jMINextSong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.META_MASK));
        jMINextSong.setText("Next Song");
        jMINextSong.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMINextSongActionPerformed(evt);
            }
        });
        JMControls.add(jMINextSong);

        jCBMIRepeatFromTheBeginning.setSelected(true);
        jCBMIRepeatFromTheBeginning.setText("Repeat From The Beginning");
        jCBMIRepeatFromTheBeginning.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCBMIRepeatFromTheBeginningActionPerformed(evt);
            }
        });
        JMControls.add(jCBMIRepeatFromTheBeginning);

        jMenuBar1.add(JMControls);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLInfo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-322)/2, 400, 322);
    }// </editor-fold>//GEN-END:initComponents

    private void jMINextSongActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMINextSongActionPerformed
    {//GEN-HEADEREND:event_jMINextSongActionPerformed
        MainWindowViewController.nextSong();
    }//GEN-LAST:event_jMINextSongActionPerformed

    private void jCBMIRepeatFromTheBeginningActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCBMIRepeatFromTheBeginningActionPerformed
    {//GEN-HEADEREND:event_jCBMIRepeatFromTheBeginningActionPerformed
        MainWindowViewController.repeatFromTheBeginning();
    }//GEN-LAST:event_jCBMIRepeatFromTheBeginningActionPerformed

    private void jMIAboutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMIAboutActionPerformed
    {//GEN-HEADEREND:event_jMIAboutActionPerformed
        MainWindowViewController.goToAboutWindow();
    }//GEN-LAST:event_jMIAboutActionPerformed

    private void initMyOwnComponents()
    {
        MainWindowViewController.initOutlets(jLInfo, jCBMIRepeatFromTheBeginning, this);
        MainWindowViewController.start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMControls;
    private javax.swing.JCheckBoxMenuItem jCBMIRepeatFromTheBeginning;
    private javax.swing.JLabel jLInfo;
    private javax.swing.JMenuItem jMIAbout;
    private javax.swing.JMenuItem jMINextSong;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
